### ISSUE TITLE
I don't find how to get allele_split.pkl 

### ISSUE THREAD

**Issue by laura1005829** [DeepRank/3D-Vac#192]

**Comment by DarioMarzella** [comment]
Hi @laura1005829, sorry for the late reply.
I am afraid it will take a little more for that. Due to changes to the paper during the review process and to make the code more usable, we are changing some details of the EGNN scripts you are trying to use: https://github.com/DeepRank/3D-Vac/pull/191/files

That will mean the allele_split.pkl file is not required anymore and the data splits can be provided as csv files.
Second, the processed pMHC 3D-models database (called "data/supervised/pandora_dataset.pt" in the version you are using) will be soon released on zenodo as part of the data of the paper, so you will be able to download it directly from there, as it is too big to be put in GitHub.

I will update you on this issue as soon as the data and code is updated and available.
Thank you a lot for your patience, and please do not hesitate to ask if you have further questions.
